steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/ash11123/gcf-artifacts/bucket_clean:prod', '.' ]
  # This step tells Google Cloud Build to use docker to build the Dockerfile.  
images:
- 'us-central1-docker.pkg.dev/ash11123/gcf-artifacts/bucket_clean:prod'
